//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppUsu.ServiceUsu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaN {
            get {
                return this.FechaNField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNField, value) != true)) {
                    this.FechaNField = value;
                    this.RaisePropertyChanged("FechaN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsu.myUsuarioIService")]
    public interface myUsuarioIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/NuevoUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/NuevoUsuarioResponse")]
        int NuevoUsuario(WebAppUsu.ServiceUsu.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/NuevoUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/NuevoUsuarioResponse")]
        System.Threading.Tasks.Task<int> NuevoUsuarioAsync(WebAppUsu.ServiceUsu.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/EditarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/EditarUsuarioResponse")]
        int EditarUsuario(WebAppUsu.ServiceUsu.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/EditarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EditarUsuarioAsync(WebAppUsu.ServiceUsu.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/EliminarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/EliminarUsuarioResponse")]
        int EliminarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/EliminarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EliminarUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/buscarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/buscarUsuarioResponse")]
        WebAppUsu.ServiceUsu.Usuario buscarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/buscarUsuario", ReplyAction="http://tempuri.org/myUsuarioIService/buscarUsuarioResponse")]
        System.Threading.Tasks.Task<WebAppUsu.ServiceUsu.Usuario> buscarUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/ListarUsuarios", ReplyAction="http://tempuri.org/myUsuarioIService/ListarUsuariosResponse")]
        WebAppUsu.ServiceUsu.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myUsuarioIService/ListarUsuarios", ReplyAction="http://tempuri.org/myUsuarioIService/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<WebAppUsu.ServiceUsu.Usuario[]> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface myUsuarioIServiceChannel : WebAppUsu.ServiceUsu.myUsuarioIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class myUsuarioIServiceClient : System.ServiceModel.ClientBase<WebAppUsu.ServiceUsu.myUsuarioIService>, WebAppUsu.ServiceUsu.myUsuarioIService {
        
        public myUsuarioIServiceClient() {
        }
        
        public myUsuarioIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public myUsuarioIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myUsuarioIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myUsuarioIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NuevoUsuario(WebAppUsu.ServiceUsu.Usuario usuario) {
            return base.Channel.NuevoUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> NuevoUsuarioAsync(WebAppUsu.ServiceUsu.Usuario usuario) {
            return base.Channel.NuevoUsuarioAsync(usuario);
        }
        
        public int EditarUsuario(WebAppUsu.ServiceUsu.Usuario usuario) {
            return base.Channel.EditarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> EditarUsuarioAsync(WebAppUsu.ServiceUsu.Usuario usuario) {
            return base.Channel.EditarUsuarioAsync(usuario);
        }
        
        public int EliminarUsuario(int idUsuario) {
            return base.Channel.EliminarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> EliminarUsuarioAsync(int idUsuario) {
            return base.Channel.EliminarUsuarioAsync(idUsuario);
        }
        
        public WebAppUsu.ServiceUsu.Usuario buscarUsuario(int idUsuario) {
            return base.Channel.buscarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<WebAppUsu.ServiceUsu.Usuario> buscarUsuarioAsync(int idUsuario) {
            return base.Channel.buscarUsuarioAsync(idUsuario);
        }
        
        public WebAppUsu.ServiceUsu.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<WebAppUsu.ServiceUsu.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
    }
}
